version: "3.8"

services:
  redis-node-1:
    image: redis:7.2.3
    container_name: node1
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-1-data:/data
      - ./cluster/redis-node-1-conf:/usr/local/etc/redis
    network_mode: host

  redis-node-2:
    image: redis:7.2.3
    container_name: node2
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-2-data:/data
      - ./cluster/redis-node-2-conf:/usr/local/etc/redis
    network_mode: host

  redis-node-3:
    image: redis:7.2.3
    container_name: node3
    command: redis-server --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-3-data:/data
      - ./cluster/redis-node-3-conf:/usr/local/etc/redis
    network_mode: host

  redis-node-4:
    image: redis:7.2.3
    container_name: node4
    command: redis-server --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-4-data:/data
      - ./cluster/redis-node-4-conf:/usr/local/etc/redis
    network_mode: host

  redis-node-5:
    image: redis:7.2.3
    container_name: node5
    command: redis-server --port 6385 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-5-data:/data
      - ./cluster/redis-node-5-conf:/usr/local/etc/redis
    network_mode: host

  redis-node-6:
    image: redis:7.2.3
    container_name: node6
    command: redis-server --port 6386 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - ./cluster/redis-node-6-data:/data
      - ./cluster/redis-node-6-conf:/usr/local/etc/redis
    network_mode: host

  redis-cluster-init:
    image: redis:7.2.3
    container_name: node_init
    command: redis-server --port 6379
    network_mode: host
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    volumes:
      - ./init-cluster.sh:/init-cluster.sh
    entrypoint: /bin/sh /init-cluster.sh
    environment:
      - "IP_HOST=127.0.0.1"
      - "NODE_1_PORT=6381"
      - "NODE_2_PORT=6382"
      - "NODE_3_PORT=6383"
      - "NODE_4_PORT=6384"
      - "NODE_5_PORT=6385"
      - "NODE_6_PORT=6386"
